// Copyright (C) 2026 Yota Hamada
// SPDX-License-Identifier: GPL-3.0-or-later

// Package runenv defines environment variable keys shared across DAG run layers.
package runenv

import "strings"

// Environment variable keys that are automatically set by Dagu during execution.
const (
	// EnvKeyDAGName holds the name of the currently executing DAG.
	EnvKeyDAGName = "DAG_NAME"

	// EnvKeyDAGRunID holds the unique identifier for the current DAG run.
	EnvKeyDAGRunID = "DAG_RUN_ID"

	// EnvKeyDAGRunLogFile holds the path to the main log file for the DAG run.
	EnvKeyDAGRunLogFile = "DAG_RUN_LOG_FILE"

	// EnvKeyDAGRunStepName holds the name of the currently executing step.
	EnvKeyDAGRunStepName = "DAG_RUN_STEP_NAME"

	// EnvKeyDAGRunStepStdoutFile holds the path to the stdout log file for the current step.
	EnvKeyDAGRunStepStdoutFile = "DAG_RUN_STEP_STDOUT_FILE"

	// EnvKeyDAGRunStepStderrFile holds the path to the stderr log file for the current step.
	EnvKeyDAGRunStepStderrFile = "DAG_RUN_STEP_STDERR_FILE"

	// EnvKeyDAGUOutputFile holds the file path used for declared step outputs.
	EnvKeyDAGUOutputFile = "DAGU_OUTPUT_FILE"

	// EnvKeyDAGRunStatus holds the current status of the DAG run (e.g., "running", "success", "failed").
	EnvKeyDAGRunStatus = "DAG_RUN_STATUS"

	// EnvKeyDAGWaitingSteps holds comma-separated step names that require manual action.
	EnvKeyDAGWaitingSteps = "DAG_WAITING_STEPS"

	// EnvKeyDAGParamsJSON exposes the resolved parameters encoded as JSON.
	// When params were provided as JSON, the original payload is preserved.
	EnvKeyDAGParamsJSON = "DAG_PARAMS_JSON"

	// EnvKeyDAGParamsJSONCompat exposes the resolved parameters encoded as JSON.
	EnvKeyDAGParamsJSONCompat = "DAGU_PARAMS_JSON"

	// EnvKeyDAGWikiDir holds the per-DAG Wiki directory path.
	EnvKeyDAGWikiDir = "DAG_WIKI_DIR"

	// EnvKeyDAGDocsDir is the deprecated name for EnvKeyDAGWikiDir.
	EnvKeyDAGDocsDir = "DAG_DOCS_DIR"

	// EnvKeyDAGRunWorkDir holds the path to the per-DAG-run working directory.
	EnvKeyDAGRunWorkDir = "DAG_RUN_WORK_DIR"

	// EnvKeyDAGRunArtifactsDir holds the path to the per-DAG-run artifacts directory.
	EnvKeyDAGRunArtifactsDir = "DAG_RUN_ARTIFACTS_DIR"

	// EnvKeyDAGPushBack exposes the current push-back iteration and history as JSON.
	EnvKeyDAGPushBack = "DAG_PUSHBACK"

	// EnvKeyDAGPushBackIteration exposes the current push-back iteration as a plain value.
	EnvKeyDAGPushBackIteration = "DAG_PUSHBACK_ITERATION"

	// EnvKeyDAGPushBackPreviousStdoutFile exposes the previous stdout log path for a pushed-back step.
	EnvKeyDAGPushBackPreviousStdoutFile = "DAG_PUSHBACK_PREVIOUS_STDOUT_FILE"

	// EnvKeyExternalStepRetry enables parent-managed step retries for sub-DAG runs.
	// When set, retriable step failures transition to a queued retry state instead of
	// sleeping inline inside the child DAG process.
	EnvKeyExternalStepRetry = "DAGU_EXTERNAL_STEP_RETRY"

	// EnvKeyQueueDispatchRetry marks an internal retry invocation that is consuming
	// an already-queued run from the scheduler/worker queue dispatch path.
	EnvKeyQueueDispatchRetry = "DAGU_QUEUE_DISPATCH_RETRY"

	// EnvKeyDAGDefinitionID carries the stable persistence identity into subprocesses.
	EnvKeyDAGDefinitionID = "DAGU_DAG_DEFINITION_ID"

	// EnvKeyParallelItem carries parallel child-run identity into subprocesses.
	EnvKeyParallelItem = "DAGU_PARALLEL_ITEM"
)

// EnvKeyPWD holds the resolved working directory of the executing step.
const EnvKeyPWD = "PWD"

// reservedRunEnvNames are the environment variable names Dagu generates for a
// run or a step. They describe one run on one host, so an authored workflow may
// neither define them nor carry them into another run.
var reservedRunEnvNames = []string{
	EnvKeyDAGName,
	EnvKeyDAGRunID,
	EnvKeyDAGRunLogFile,
	EnvKeyDAGRunStepName,
	EnvKeyDAGRunStepStdoutFile,
	EnvKeyDAGRunStepStderrFile,
	EnvKeyDAGRunStatus,
	EnvKeyDAGWikiDir,
	EnvKeyDAGDocsDir,
	EnvKeyDAGParamsJSON,
	EnvKeyDAGParamsJSONCompat,
	EnvKeyDAGRunWorkDir,
	EnvKeyDAGRunArtifactsDir,
	EnvKeyDAGPushBack,
	EnvKeyDAGPushBackIteration,
	EnvKeyDAGPushBackPreviousStdoutFile,
	EnvKeyExternalStepRetry,
	EnvKeyQueueDispatchRetry,
}

// ReservedRunEnvNames returns the run-managed environment variable names.
func ReservedRunEnvNames() []string {
	return append([]string(nil), reservedRunEnvNames...)
}

// isReservedRunEnvKey reports whether key is generated by Dagu for a run or a
// step rather than authored by a workflow. It matches ReservedRunEnvNames
// exactly.
//
// Matching ignores case on every platform. Environment names are
// case-insensitive on Windows, so a case-sensitive test would let a lowercase
// spelling resolve to the managed value and slip past this check there. The
// cost is that a workflow cannot claim a name that differs only in case, which
// keeps the answer the same on every platform.
func isReservedRunEnvKey(key string) bool {
	for _, reserved := range reservedRunEnvNames {
		if strings.EqualFold(key, reserved) {
			return true
		}
	}
	return false
}

// nonTransferableExtraNames are generated per run or per step but are absent
// from reservedRunEnvNames, which authored-name validation also consumes and
// which has always permitted them. They still must not cross a run boundary:
// each one addresses the run or step that produced it.
var nonTransferableExtraNames = []string{
	EnvKeyPWD,
	EnvKeyDAGUOutputFile,
	EnvKeyDAGWaitingSteps,
	EnvKeyDAGDefinitionID,
	EnvKeyParallelItem,
}

// IsNonTransferableRunEnvKey reports whether key must not cross a run boundary.
// It covers the run-managed names plus the per-run and per-step values that
// authored-name validation still allows a workflow to define.
func IsNonTransferableRunEnvKey(key string) bool {
	if isReservedRunEnvKey(key) {
		return true
	}
	for _, name := range nonTransferableExtraNames {
		if strings.EqualFold(key, name) {
			return true
		}
	}
	return false
}
